dist: trusty
language: java
jdk: oraclejdk8
env:
    - COVERAGE=0.057 ./gradlew -p ./monolithic/ui check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/cart check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/user check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/order check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/cart check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/product check
    - COVERAGE=0.057 ./gradlew -p ./monolithic/user check
stages:
    - build
    - test
    - deploy
jobs:
    include:
      - stage: build
        name : build
        script:
            - ./gradlew clean jar 
      - stage: test
        name: tast
        script:
            - echo 'testing'
        after_success:
            - $COVERAGE 
      - stage: deploy
        provider: script
        script: echo 'WIP'
        on:
            all_branches: true

