dist: trusty
language: java
jdk: oraclejdk8
env:
    - COVERAGE=0.057 ./gradlew -p ./monolithic/ui 
    - COVERAGE=0.057 ./gradlew -p ./monolithic/cart
    - COVERAGE=0.057 ./gradlew -p ./monolithic/user
    - COVERAGE=0.057 ./gradlew -p ./monolithic/order
    - COVERAGE=0.057 ./gradlew -p ./monolithic/cart
    - COVERAGE=0.057 ./gradlew -p ./monolithic/product
    - COVERAGE=0.057 ./gradlew -p ./monolithic/user 

before_script:
    - ./gradlew clean jar 
script:
    - $COVERAGE check
    - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
deploy:
    provider: script
    script: echo 'WIP'
    on:
       all_branches: true

