dist: trusty
language: java
jdk: oraclejdk8
services:
    - docker
stages:
    - build
    - test
    - deploy
jobs:
    include:
      - stage: build
        name : build
        script:
            - ./gradlew clean jar 
      - stage: test
        name: test
        script:
            - ./gradlew test
        after_success:
            - ./gradlew jacocoTestReport	    
            - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'	    
            - ./gradlew jacocoTestCoverageVerification
      - stage: deploy
        provider: script
        script:  bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\"
        --password-stdin ;"
        on:
            all_branches: true

