dist: trusty
language: java
jdk: oraclejdk8
sudo: required	
services:
    - docker
before_install:
    - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
install:
    - "./gradlew clean jar"

script: 
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - ./gradlew jacocoTestCoverageVerification
     
after_success:  	    
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'	
before_deploy:
    - ./gradlew -p ./monolithic/ui packageToContainer ;    
deploy:
    provider: script
    script: "./script/deploy.sh"
       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
    on:
    condition: "$BUILD_TARGET == './monolithic/ui'"
    branch: master  
      
