dist: trusty
language: java
jdk: oraclejdk8


install:
    - ./.gradlew clean jar 
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
       - $HOME/.gradle/caches/modules-2/
       - $HOME/.gradle/wrapper/dists/
script:
    - echo 'testing coming soon '