dist: trusty
language: java
jdk: oraclejdk8
sudo: required	
services:
    - docker
before_install:
    - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
install:
    - "./gradlew clean jar"

script: 
    - ./gradlew test
    - ./gradlew jacocoTestReport
     
after_success:  	    
    - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'	
    - ./gradlew jacocoTestCoverageVerification

before_deploy:
    - ./gradlew -p ./monolithic/ui packageToContainer ;    
deploy:
    provider: script
    script: "./script/deploy.sh"
    after_success:
    #!/usr/bin/env bash
    set -e

    "echo \"${DOCKER_PASS}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"
    docker tag zutherb/monolithic-shop:latest ${DOCKER_LOGIN}/theapp:latest
    docker push ${DOCKER_LOGIN}/monolithic-shop:latest
    on:
    condition: "$BUILD_TARGET == './monolithic/ui'"
    branch: master  
      
